### ISSUE TITLE
Bug: Accusta shows error while trying to see Power down statistics

### ISSUE THREAD

**Issue by sourovafrin** [semasping/Accusta#2]
#### Expected behavior

Accusta shows account statistics for steemit blockchain. This website shows weekly and monthly data grouping of posts, author rewards and curation rewards.
And also show steem power down statistics, history of account wallet with filters and witness rewards.

#### Actual behavior

I was able to check all those thing without **Steem power down statistics** . When i tried to check my steem power down statistics it showed a error.
#### How to reproduce

- Open your browser and go to https://steemit.accusta.tk/

- Put your username in the box and click on **View statistics**

- It will land you to **Monthly statistics**

- Now click on **Power down statistics**

- It will load for a while and will show you a error

* Browser version: Google Chrome Version 66.0.3359.181 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug
https://youtu.be/9xfNwp9RvRg

##### Optional bug
https://youtu.be/lkewETNq-J0

**Comment by semasping** [comment]
Thanks for the detailed description
Try now.

**Comment by sourovafrin** [comment]
Yeah, it is fixed now.
